Fixed bingo get fails on Windows
bwplotka/bingo pull request #155
Opened 2024-11-07 09:31 UTC by melvinmurvie

This PR is to make sure opened files are closed immediately (instead of at defer) if we don't need it anymore.

On Windows an error occurs when we try to rename from/to an opened files. Calling `os.Rename(old, new)` we should make sure to close both `old` and `new` files (if `new` is existed and opened).

Fixes #127

2025-01-24 09:43 UTC, bwplotka requested changes
Thanks so much for helping!

I gave some suggestions on a bit cleaner approach, but good progress and thanks for approaching this! 💪🏽

2025-01-24 09:43 UTC, bwplotka commented on get.go
> +			if err := mf.Close(); err != nil {
Thanks! Can we ensure we don't use `mf` variable after Close? Here we can do easily with `dpkg := *mf.DirectPackage()` and then close and then append to target (:

2025-01-24 09:43 UTC, bwplotka commented on get.go
> +			if err := mf.Close(); err != nil {
ditto. We can't use `mf` after Close even if by accident in this code we can.

2025-01-24 09:43 UTC, bwplotka commented on get.go
> +	if err := tmpModFile.Close(); err != nil {
Same here, it's not acceptable to use `tmpModFile` var that is closed. It might work by accident now, but will cause surprises later on.

Why not closing right before `os.Rename` (and saving tmpModFile fileapath to variable?)

2025-01-25 03:54 UTC, melvinmurvie commented
> Thanks so much for helping!
> 
> I gave some suggestions on a bit cleaner approach, but good progress and thanks for approaching this! 💪🏽

@bwplotka Thanks for the suggestions! I've already made the changes, please take a look and let me know if there's anything else need to improve! 🙏🏽

2025-11-05 08:48 UTC, bwplotka approved these changes
Thanks!

2025-11-05 08:48 UTC, merged